version: '3.1'

services:

  mcbot:
    container_name: mcbot
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"