# Generated by Django 3.2.5 on 2021-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='type',
            field=models.CharField(default='Пополнение', max_length=255, verbose_name='тип транзакции'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='type',
            field=models.CharField(default='Вывод стредств', max_length=255, verbose_name='тип транзакции'),
        ),
    ]
