# Generated by Django 3.2.5 on 2021-08-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20210803_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[(1, 'В ожидании'), (2, 'Оплачено'), (3, 'Истекший'), (4, 'Отклонено')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[(1, 'В процессе'), (2, 'Исполнено'), (3, 'Отклонено')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='type',
            field=models.CharField(default='Вывод средств', max_length=255, verbose_name='тип транзакции'),
        ),
    ]
