# Generated by Django 3.2.5 on 2021-08-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20210803_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
    ]
