# Generated by Django 3.2.5 on 2021-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20210803_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepost',
            name='headline',
            field=models.CharField(help_text='максимум 56 символов', max_length=56, verbose_name='Заголовок'),
        ),
    ]
