# Generated by Django 3.2.5 on 2021-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_mainpagepost_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='accounts/image', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='mainpagepost',
            name='headline',
            field=models.CharField(help_text='максимум 36 символов', max_length=36, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpagepost',
            name='subtitle',
            field=models.CharField(max_length=120, verbose_name='Подзаголовок'),
        ),
    ]
