# Generated by Django 3.2.5 on 2021-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewsettings',
            name='image',
            field=models.URLField(default='https://doszhan.space/media/2607211245970578.png', help_text='Данное поле для всех страниц. Для сертификатов подставляется своя картинка', max_length=255, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='previewsettings',
            name='url',
            field=models.URLField(default='https://doszhan.space', help_text='Данное поле для всех страниц. Для сертификатов подставляется свой url', max_length=255, verbose_name='Ссылка на сайт'),
        ),
    ]
