# Generated by Django 3.2.5 on 2021-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20210820_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagepost',
            name='photo',
            field=models.FileField(blank=True, default='def/default-user-image.png', upload_to='posts', verbose_name='PostPhoto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, default='def/default-user-image.png', upload_to='avatars', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='previewsettings',
            name='image',
            field=models.URLField(default='127.0.0.1/media/2607211245970578.png', help_text='Данное поле для всех страниц. Для сертификатов подставляется своя картинка', max_length=255, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='previewsettings',
            name='url',
            field=models.URLField(default='127.0.0.1', help_text='Данное поле для всех страниц. Для сертификатов подставляется свой url', max_length=255, verbose_name='Ссылка на сайт'),
        ),
    ]
