# Generated by Django 3.2.5 on 2021-08-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_certificate_is_prepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepost',
            name='headline',
            field=models.CharField(help_text='максимум 50 символов', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpagepost',
            name='subtitle',
            field=models.CharField(max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
