# Generated by Django 3.2.5 on 2021-08-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_auto_20210825_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepost',
            name='headline',
            field=models.CharField(help_text='максимум 50 символов', max_length=80, verbose_name='Заголовок'),
        ),
    ]
